import { Box, Heading, Image } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Image
                    src={"/mike-cover.jpg"}
                    w={"100vw"}
                    h={"100vh"}
                    objectFit={"cover"}
                    filter={"brightness(50%)"}
                    userSelect={"none"}
                    draggable={false}
                />
                <Heading>More content, announcements, events etc...</Heading>
            </main>
        </>
    );
}
